# Auto testing bff source code with GitHub Actions
name: Testing develop

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
      - run: echo "abc"
