# Auto testing bff source code with GitHub Actions
name: Testing develop

on:
  push:
    branches:
      - main

jobs:
  stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: deploy
        run: echo "stage"
  production:
    runs-on: ubuntu-latest
    environment: production
    needs: [stage]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: deploy
        run: echo "production"
